apiVersion: v1
kind: Service
metadata:
  name: kube-api-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/'
spec:
  ports:
    - port: 80
      name: http
  selector:
    name: kube-api-exporter
